<?php

namespace Clear\CompanyBundle\Repository;

/**
 * SpeciticThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
