<?php

namespace Clear\LogBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLogsOrderByTime($id)
    {
        return
            $query = $this->createQueryBuilder('log')
                ->where('log.content = :id')
                ->orderBy('log.createdAt', 'DESC')
                ->setParameter('id', $id)
                ->getQuery();
    }
}
