<?php

namespace Clear\UserBundle\Repository;

/**
 * DisallowedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisallowedRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByParameters($request)    
    {

        $query = $this->createQueryBuilder('d')
            ->where('d.roleUser = :role')
            ->andWhere('d.actionId = :actionId')
            ->setParameters(['role' => $request['roleUser'], 'actionId' => $request['actionId']])
            ->getQuery()
            ->getOneOrNullResult();

        return $query;
    }
}
