Clear\OAuthBundle\Entity\Client:
    type: entity
    table: client
    repositoryClass: Clear\OAuthBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
