<?php

namespace Clear\FileStorageBundle\Repository;

/**
 * FileStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileStorageRepository extends \Doctrine\ORM\EntityRepository
{
}
